USE Sales;
LOAD DATA INFILE 'regiona.tbl' REPLACE INTO TABLE Sales.Region FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'nation.tbl' REPLACE INTO TABLE Sales.Nation FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'supplier.tbl' REPLACE INTO TABLE Sales.Supplier FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'part.tbl' REPLACE INTO TABLE Sales.Part FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'partsupp.tbl' REPLACE INTO TABLE Sales.PartSupp FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'customer.tbl' REPLACE INTO TABLE Sales.Customer FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'orders.tbl' REPLACE INTO TABLE Sales.Orders FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
-- LOAD DATA INFILE 'lineitem.tbl' REPLACE INTO TABLE Sales.Lineitem FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';