CREATE USER David IDENTIFIED BY '123456';
CREATE USER Tom IDENTIFIED BY '123456';
CREATE USER Kathy IDENTIFIED BY '123456';
GRANT CREATE ROLE ON *.* TO 'David'@'%';
GRANT CREATE ROLE ON *.* TO 'Tom'@'%';
GRANT CREATE ROLE ON *.* TO 'Kathy'@'%';
FLUSH PRIVILEGES;

CREATE USER Jeffery IDENTIFIED BY '123456';
CREATE USER Jane IDENTIFIED BY '123456';
CREATE USER Mike IDENTIFIED BY '123456';